apiVersion: "v1"
kind: "Secret"
metadata:
  name: database-secrets
  labels:
    app: { { template "fullname" . } }
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  user: root
  password: root
